# Generated by Django 3.1 on 2020-09-02 20:42

import django.core.validators
from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propty',
            name='finish_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Unfinished'), (2, 'Semi Finished'), (3, 'Fully Finished'), (4, 'Lux'), (5, 'Super Lux'), (6, 'Ultra Lux'), (7, 'Deluxe')], null=True),
        ),
        migrations.AlterField(
            model_name='propty',
            name='flooring',
            field=models.IntegerField(blank=True, choices=[(1, 'Marble'), (2, 'Hardwood'), (3, 'Ceramic Tile'), (4, 'Stone'), (5, 'Parquet'), (6, 'Softwood'), (7, 'Non Ceramic Tile'), (8, 'Laminate'), (9, 'Linoleum')], null=True),
        ),
        migrations.AlterField(
            model_name='propty',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propty',
            name='number_of_balconies',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propty',
            name='payment_method',
            field=models.IntegerField(blank=True, choices=[(1, 'Cash'), (2, 'Installments')], null=True),
        ),
        migrations.AlterField(
            model_name='propty',
            name='storeys',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Duplex'), (3, 'Triplex')], null=True),
        ),
        migrations.AlterField(
            model_name='propty',
            name='view',
            field=models.IntegerField(blank=True, choices=[(1, 'Corner'), (2, 'Water'), (3, 'Main Street'), (4, 'Side Street'), (5, 'Garden'), (6, 'Yard')], null=True),
        ),
        migrations.AlterField(
            model_name='propty',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), listings.models.max_value_current_year]),
        ),
    ]
