# Generated by Django 3.1 on 2020-09-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200902_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
