# Generated by Django 3.1 on 2020-09-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200906_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propty',
            old_name='has_bool',
            new_name='has_pool',
        ),
    ]
