# Generated by Django 3.1 on 2020-09-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200907_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propty',
            old_name='available_on',
            new_name='available_from',
        ),
    ]
