# Generated by Django 3.1 on 2020-09-01 21:48

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=accounts.models.EmptyStringToNoneField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
